# action.yml
name: 'CodeMaker Pull Request Action'
description: 'Auto update pull request based on user comments.'
branding:
  icon: 'code'
  color: 'blue'
inputs:
  access-token:
    description: 'GitHub Personal Access Token (PAT) with write access to your repository'
    required: true
  api-key:
    description: 'CodeMaker API Key'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
